<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SeedSectionsTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
        DB::table('sections')->insert(
        	array(
				array('name' => 'Abbiategrasso'),
				array('name' => 'Acireale'),
				array('name' => 'Adria'),
				array('name' => 'Agrigento'),
				array('name' => 'Agropoli'),
				array('name' => 'Albano Laziale'),
				array('name' => 'Albenga'),
				array('name' => 'Alessandria'),
				array('name' => 'Alghero'),
				array('name' => 'Ancona'),
				array('name' => 'Aosta'),
				array('name' => 'Aprilia'),
				array('name' => 'Arco Riva'),
				array('name' => 'Arezzo'),
				array('name' => 'Ariano Irpino'),
				array('name' => 'Ascoli Piceno'),
				array('name' => 'Asti'),
				array('name' => 'Avellino'),
				array('name' => 'Avezzano'),
				array('name' => 'Barcellona Pozzo di Gotto'),
				array('name' => 'Bari'),
				array('name' => 'Barletta'),
				array('name' => 'Bassano del Grappa'),
				array('name' => 'Battipaglia'),
				array('name' => 'Belluno'),
				array('name' => 'Benevento'),
				array('name' => 'Bergamo'),
				array('name' => 'Bernalda'),
				array('name' => 'Biella'),
				array('name' => 'Bologna'),
				array('name' => 'Bolzano'),
				array('name' => 'Bra\''),
				array('name' => 'Brescia'),
				array('name' => 'Brindisi'),
				array('name' => 'Busto Arsizio'),
				array('name' => 'Cagliari'),
				array('name' => 'Caltanissetta'),
				array('name' => 'Campobasso'),
				array('name' => 'Carbonia'),
				array('name' => 'Carrara'),
				array('name' => 'Casale Monferrato'),
				array('name' => 'Casarano'),
				array('name' => 'Caserta'),
				array('name' => 'Cassino'),
				array('name' => 'Castelfranco Veneto'),
				array('name' => 'Castellammare di Stabia'),
				array('name' => 'Catania'),
				array('name' => 'Catanzaro'),
				array('name' => 'Cervignano del Friuli'),
				array('name' => 'Cesena'),
				array('name' => 'Chiari'),
				array('name' => 'Chiavari'),
				array('name' => 'Chieti'),
				array('name' => 'Chioggia'),
				array('name' => 'Chivasso'),
				array('name' => 'Ciampino'),
				array('name' => 'Citta\' di Castello'),
				array('name' => 'Civitavecchia'),
				array('name' => 'Collegno'),
				array('name' => 'Como'),
				array('name' => 'Conegliano'),
				array('name' => 'Cormons'),
				array('name' => 'Cosenza'),
				array('name' => 'Crema'),
				array('name' => 'Cremona'),
				array('name' => 'Crotone'),
				array('name' => 'Cuneo'),
				array('name' => 'Empoli'),
				array('name' => 'Enna'),
				array('name' => 'Ercolano'),
				array('name' => 'Este'),
				array('name' => 'Faenza'),
				array('name' => 'Fermo'),
				array('name' => 'Ferrara'),
				array('name' => 'Finale Emilia'),
				array('name' => 'Firenze'),
				array('name' => 'Foggia'),
				array('name' => 'Foligno'),
				array('name' => 'Forli\''),
				array('name' => 'Formia'),
				array('name' => 'Frattamaggiore'),
				array('name' => 'Frosinone'),
				array('name' => 'Gallarate'),
				array('name' => 'Genova'),
				array('name' => 'Gorizia'),
				array('name' => 'Grosseto'),
				array('name' => 'Gubbio'),
				array('name' => 'Imola'),
				array('name' => 'Imperia'),
				array('name' => 'Isernia'),
				array('name' => 'Ivrea'),
				array('name' => 'Jesi'),
				array('name' => 'Lamezia Terme'),
				array('name' => 'Lanciano'),
				array('name' => 'L\'Aquila'),
				array('name' => 'La Spezia'),
				array('name' => 'Latina'),
				array('name' => 'Latisana'),
				array('name' => 'Lecce'),
				array('name' => 'Lecco'),
				array('name' => 'Legnago'),
				array('name' => 'Legnano'),
				array('name' => 'Livorno'),
				array('name' => 'Locri'),
				array('name' => 'Lodi'),
				array('name' => 'Lomellina'),
				array('name' => 'Lovere'),
				array('name' => 'Lucca'),
				array('name' => 'Lugo di Romagna'),
				array('name' => 'Macerata'),
				array('name' => 'Maniago'),
				array('name' => 'Mantova'),
				array('name' => 'Marsala'),
				array('name' => 'Matera'),
				array('name' => 'Merano'),
				array('name' => 'Messina'),
				array('name' => 'Mestre'),
				array('name' => 'Milano'),
				array('name' => 'Modena'),
				array('name' => 'Molfetta'),
				array('name' => 'Moliterno'),
				array('name' => 'Monfalcone'),
				array('name' => 'Monza'),
				array('name' => 'Napoli'),
				array('name' => 'Nichelino'),
				array('name' => 'Nocera Inferiore'),
				array('name' => 'Nola'),
				array('name' => 'Novara'),
				array('name' => 'Novi Ligure'),
				array('name' => 'Nuoro'),
				array('name' => 'Olbia'),
				array('name' => 'Oristano'),
				array('name' => 'Orvieto'),
				array('name' => 'Ostia Lido'),
				array('name' => 'Ozieri'),
				array('name' => 'Padova'),
				array('name' => 'Palermo'),
				array('name' => 'Paola'),
				array('name' => 'Parma'),
				array('name' => 'Pavia'),
				array('name' => 'Perugia'),
				array('name' => 'Pesaro'),
				array('name' => 'Pescara'),
				array('name' => 'Piacenza'),
				array('name' => 'Pinerolo'),
				array('name' => 'Piombino'),
				array('name' => 'Pisa'),
				array('name' => 'Pistoia'),
				array('name' => 'Pontedera'),
				array('name' => 'Pordenone'),
				array('name' => 'Portogruaro'),
				array('name' => 'Potenza'),
				array('name' => 'Prato'),
				array('name' => 'Ragusa'),
				array('name' => 'Ravenna'),
				array('name' => 'Reggio Calabria'),
				array('name' => 'Reggio Emilia'),
				array('name' => 'Rieti'),
				array('name' => 'Rimini'),
				array('name' => 'Roma 1'),
				array('name' => 'Roma 2'),
				array('name' => 'Rossano'),
				array('name' => 'Rovereto'),
				array('name' => 'Rovigo'),
				array('name' => 'Sala Consilina'),
				array('name' => 'Salerno'),
				array('name' => 'San Benedetto del Tronto'),
				array('name' => 'San Dona\' di Piave'),
				array('name' => 'Sapri'),
				array('name' => 'Saronno'),
				array('name' => 'Sassari'),
				array('name' => 'Savona'),
				array('name' => 'Schio'),
				array('name' => 'Seregno'),
				array('name' => 'Sesto San Giovanni'),
				array('name' => 'Siena'),
				array('name' => 'Siracusa'),
				array('name' => 'Sondrio'),
				array('name' => 'Soverato'),
				array('name' => 'Sulmona'),
				array('name' => 'Taranto'),
				array('name' => 'Taurianova'),
				array('name' => 'Teramo'),
				array('name' => 'Termoli'),
				array('name' => 'Terni'),
				array('name' => 'Tivoli'),
				array('name' => 'Tolmezzo'),
				array('name' => 'Torino'),
				array('name' => 'Torre Annunziata'),
				array('name' => 'Torre del Greco'),
				array('name' => 'Tortoli\''),
				array('name' => 'Trapani'),
				array('name' => 'Trento'),
				array('name' => 'Treviglio'),
				array('name' => 'Treviso'),
				array('name' => 'Trieste'),
				array('name' => 'Udine'),
				array('name' => 'Valdarno'),
				array('name' => 'Varese'),
				array('name' => 'Vasto'),
				array('name' => 'VCO'),
				array('name' => 'Venezia'),
				array('name' => 'Venosa'),
				array('name' => 'Vercelli'),
				array('name' => 'Verona'),
				array('name' => 'Viareggio'),
				array('name' => 'Vibo Valentia'),
				array('name' => 'Vicenza'),
				array('name' => 'Viterbo'),
				array('name' => 'Voghera'),            
			)
		);
	}

	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		DB::table('sections')->delete();
	}

}
